### ISSUE TITLE
< waiting for any device > 

### ISSUE THREAD

**Issue by ghost** [nathanchance/chromeos-adb-fastboot#3]
So I have installed everything but not all of it seems to work. If I try to flash it won't recognize it but if I try to boot it works fine. Also flash-all.sh don't find the device when fastboot devices does? Any help? [screenshot](https://dl.xda-developers.com/4/6/4/6/2/0/9/Screenshot_2018-11-18_at_12.03.43_PM.png?key=ms-Dc6DeeINGeTmLhKRxCA&ts=1542561469)

**Comment by ghost** [comment]
side note: so I managed to flash the factory image by just opening the flash-all.sh and doing all commands manually... So that fixed the "can't flash" but now I'm wondering why flash-all.sh doesn't work?

**Comment by nathanchance** [comment]
I can't see your screenshot but you need to run the `flash-all.sh` script with `source`.

`source ./flash-all.sh`

If you try to run it in a subshell, it won't use the proper fastboot wrapper that I have set up.

**Comment by ghost** [comment]
Ohhh thanks! I'll try that also the screenshot is attached to xda reply I sent on the [Guide] Thread. But thanks!
